apps/blog/urls.py
from django.urls import path

from apps.blog.views import BlogDetailPageView, BlogPageView

from . import views

app_name = "blog"
urlpatterns = [
    path("", BlogPageView.as_view(), name="blogs"),
    path("blog/<slug:slug>/", BlogDetailPageView.as_view(), name="blog_detail_page"),
    path("tag/<slug:slug>/", views.TagDetailView.as_view(), name="tag_detail_page"),
    path(
        "category/<slug:slug>/",
        views.CategoryDetailView.as_view(),
        name="category_detail_page",
    ),
    path("author/<slug:slug>/", views.BlogAuthorView.as_view(), name="author"),
    path("search/", views.SearchView.as_view(), name="search"),
]

apps/home/urls.py
from django.urls import path

from .views import HomePageView

app_name = "home"
urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

admin.site.site_title = "Dashboard"
admin.site.site_header = "The Visionarys Nepal"
admin.site.index_title = "The Visionarys Nepal (TVN)"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.home.urls")),
    path("blogs/", include("apps.blog.urls")),
    path("teams/", include("apps.team.urls")),
    path("contact/", include("apps.contact.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/blog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)

        return super(Tag, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} Tag"


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    slug = models.SlugField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)

        return super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"


class Blog(models.Model):
    title = models.CharField(max_length=255)
    headline = models.CharField(max_length=255, blank=True, null=True)
    content = RichTextUploadingField()
    last_updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(null=True, blank=True, upload_to="blogs/")
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="blog_author",
    )
    tags = models.ManyToManyField(Tag, blank=True, related_name="blog_tags")
    view_count = models.IntegerField(null=True, blank=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="blog_category",
    )

    def __str__(self):
        return f"{self.title}"

    @property
    def get_author_name(self):
        return self.author.profile.get_name


class Comment(models.Model):
    user_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    content = models.TextField()
    date = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    parent = models.ForeignKey(
        "self",
        on_delete=models.DO_NOTHING,
        blank=True,
        null=True,
        related_name="replies",
    )

    def __str__(self):
        return f"{self.user_name}"

apps/blog/forms.py
from django import forms

from apps.blog.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {"user_name", "email", "content"}

        widgets = {
            "user_name": forms.TextInput(
                attrs={"placeholder": "Your Name*", "class": "form-control"}
            ),
            "email": forms.EmailInput(
                attrs={"placeholder": "Your Email*", "class": "form-control"}
            ),
            "content": forms.Textarea(
                attrs={"placeholder": "Your comment*", "class": "form-control"}
            ),
        }

apps/blog/views.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView, TemplateView

from apps.blog.forms import CommentForm
from apps.blog.models import Blog, Category, Comment, Tag


# Create your views here.
class BlogPageView(TemplateView):
    template_name = "blog/blogs.html"

    def get_context_data(self, **kwargs):
        super().get_context_data(**kwargs)
        blogs = (
            Blog.objects.all()
            .select_related("author", "category")
            .order_by("-view_count")
        )
        page_num = self.request.GET.get("q")
        paginator = Paginator(blogs, 6)
        page_obj = paginator.get_page(page_num)

        context = {"blogs": page_obj}
        return context


class BlogDetailPageView(DetailView):
    model = Blog
    template_name = "blog/blog_detail.html"

    def get_object(self, queryset=None):
        qs = (
            Blog.objects.select_related("author", "category")
            .prefetch_related(
                "comments",
                "comments__parent",
                "comments__replies",
                "author__user_socials__icon",
            )
            .annotate(total_comments=Count("comments", filter=Q(comments__parent=None)))
        )
        return get_object_or_404(qs, slug=self.kwargs["slug"])

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        blog = self.get_object()
        recent_blogs = Blog.objects.all().order_by("-last_updated")
        tags = Tag.objects.all()
        comment_form = CommentForm()
        categories = Category.objects.annotate(
            total_blogs=Count("blog_category", distinct=True)
        ).order_by("-total_blogs")

        if blog.view_count is None:
            blog.view_count = 1
        else:
            blog.view_count = blog.view_count + 1
        blog.save()

        query = self.request.GET.get("q")
        if query is not None and query != "":
            blogs = Blog.objects.filter(title__icontains=query)

        context = {
            "post": blog,
            "comment_form": comment_form,
            "recent_blogs": recent_blogs,
            "tags": tags,
            "categories": categories,
        }

        return context

    def post(self, request, *args, **kwargs):
        slug = kwargs.get("slug")
        blog_post = self.get_object()
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid:
            if request.POST.get("parent_id"):
                parent_id = request.POST.get("parent_id")
                parent = Comment.objects.get(id=parent_id)
                if parent:
                    comment_reply = comment_form.save(commit=False)
                    comment_reply.parent = parent
                    comment_reply.post = blog_post
                    comment_reply.save()
                    return render(
                        request,
                        "blog/includes/comments.html",
                        {
                            "post": self.get_object(),
                            "comment_form": CommentForm(),
                        },
                    )
            else:
                comment = comment_form.save(commit=False)
                comment.post = blog_post
                comment.save()
                return render(
                    request,
                    "blog/includes/comments.html",
                    {
                        "post": self.get_object(),
                        "comment_form": CommentForm(),
                    },
                )
        return JsonResponse({"error": "Invalid Form", "status": "500"})


class TagDetailView(DetailView):
    model = Tag
    template_name = "blog/tag_page.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Tag, slug=self.kwargs["slug"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tags = Tag.objects.exclude(slug=self.kwargs["slug"])
        tag = self.get_object()
        blogs = Blog.objects.select_related("category", "author")
        top_blogs = blogs.filter(tags__slug=tag.slug).order_by("-view_count")[:3]
        recent_blogs = blogs.filter(tags__slug=tag.slug).order_by("-last_updated")[:3]
        context.update(
            {
                "tag": tag,
                "tags": tags,
                "top_blogs": top_blogs,
                "recent_blogs": recent_blogs,
            }
        )

        return context


class BlogAuthorView(DetailView):
    template_name = "blog/author.html"
    model = User

    def get_object(self, queryset=None):
        qs = User.objects.select_related("profile").prefetch_related(
            "blog_author", "blog_author__category"
        )
        return get_object_or_404(qs, profile__slug=self.kwargs["slug"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = self.get_object()
        top_authors = (
            User.objects.select_related("profile")
            .annotate(total_blogs=Count("blog_author"))
            .order_by("-total_blogs")
        )
        top_blogs = author.blog_author.prefetch_related("category").order_by(
            "-view_count"
        )[0:3]
        recent_blogs = author.blog_author.prefetch_related("category").order_by(
            "-last_updated"
        )[0:3]
        context.update(
            {
                "author": author,
                "top_authors": top_authors,
                "top_blogs": top_blogs,
                "recent_blogs": recent_blogs,
            }
        )
        return context


class CategoryDetailView(DetailView):
    model = Category
    template_name = "blog/category_page.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Category, slug=self.kwargs["slug"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.get_object()
        categories = Category.objects.exclude(slug=self.kwargs["slug"])
        blogs = Blog.objects.select_related("author", "category")
        top_blogs = blogs.filter(category=category).order_by("-view_count")[0:3]
        recent_blogs = blogs.filter(category=category).order_by("-last_updated")[:3]
        context.update(
            {
                "category": category,
                "categories": categories,
                "top_blogs": top_blogs,
                "recent_blogs": recent_blogs,
            }
        )
        return context


class SearchView(TemplateView):
    template_name = "blog/search.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get("search")
        if query:
            blogs = Blog.objects.select_related("author", "category").filter(
                title__icontains=query
            )
            context.update(
                {
                    "blogs": blogs,
                    "query": query,
                }
            )
        return context

apps/blog/templates/blog/author.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ author.profile.get_name }}{% endblock title %}
{% load tz %}

{% block content %}
    <style>
        .cursor-pointer {
            cursor: pointer;
        }

        .meta-li {
            color: rgba(var(--default-color-rgb), 0.6);
            font-size: 14px;
            display: inline-block;
            line-height: 1;
            cursor: default;
        }

        .recent-posts .post-img {
            max-height: 180px;
        }
    </style>
    <main id="main">
        <div data-aos="fade" class="page-title">
            <div class="heading">
                <div class="container">
                    <div class="row d-flex justify-content-center text-center">
                        <div class="col-lg-8">
                            <h1>{{ author.profile.get_name }}</h1>
                            <p class="mb-0">{{ author.profile.bio }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <nav class="breadcrumbs">
                <div class="container">
                    <ol>
                        <li><a href="{% url "home:home" %}">Home</a></li>
                        <li><a href="{% url "blog:blogs" %}">Blogs</a></li>
                        <li class="current">{{ author.profile.get_name }}</li>
                    </ol>
                </div>
            </nav>
        </div>

        <section id="blog-details" class="blog-details">

            <div class="container" data-aos="fade-up" data-aos-delay="100">

                <div class="row g-5">

                    <div class="col-lg-9">
                        <section id="blogs" class="recent-posts">
                            <div class="container section-title" data-aos="fade-up">
                                <h2>Top Posts</h2>
                                <p>Here are the most viewed posts of {{ author.profile.get_name }}.</p>
                            </div>
                            <div class="container">
                                <div class="row gy-4">
                                    {% for blog in top_blogs %}
                                        {% include "blog/includes/blog_card.html" with blog=blog %}
                                    {% empty %}
                                        <p>There are no posts</p>
                                    {% endfor %}
                                </div>
                            </div>

                        </section>

                        <section id="blogs" class="recent-posts">
                            <div class="container section-title" data-aos="fade-up">
                                <h2>Recent Posts</h2>
                                <p>Here are the most recent blogs from {{ author.profile.get_name }}</p>
                            </div>
                            <div class="container">
                                <div class="row gy-4">
                                    {% for blog in recent_blogs %}
                                        {% include "blog/includes/blog_card.html" with blog=blog %}
                                    {% empty %}
                                        <p>There are no posts</p>
                                    {% endfor %}
                                </div>
                            </div>

                        </section>

                    </div>

                    <div class="col-lg-3">
                        <div class="sidebar">
                            <div class="sidebar-item recent-posts">
                                <h3 class="sidebar-title">Top Authors</h3>

                                {% for author in top_authors %}
                                    <div class="post-item">
                                        {% if author.profile.profile_image %}
                                            <img src="{{ author.profile.profile_image.url }}"
                                                 alt="{{ author.get_full_name }}" class="flex-shrink-0">
                                        {% else %}
                                            <img src="{% static 'assets/img/profile.svg' %}" alt="{{ Author }}"
                                                 class="flex-shrink-0"/>
                                        {% endif %}
                                        <div>
                                            <h4>
                                                <a href="{% url "blog:author" author.profile.slug %}">{{ author.profile.get_name }}</a>
                                            </h4>
                                        </div>
                                    </div><!-- End recent post item-->
                                {% endfor %}
                            </div><!-- End sidebar recent posts-->
                        </div><!-- End Sidebar -->
                    </div>

                </div>

            </div>

        </section><!-- End Blog-details Section -->
    </main>
{% endblock content %}

apps/blog/templates/blog/blogs.html
{% extends "base.html" %}
{% load static %}
{% block title %}Blogs{% endblock title %}

{% block extra_css %}
<style>
    .post-img {
        height: 100%;
    }

    .img-fluid {
        height: 100%;
        width: 100%;
        object-position: top;
        object-fit: cover;
    }
</style>
{% endblock %}

{% block content %}
    <main id="main" style="opacity: 1;">
        <div data-aos="" class="page-title">
            <div class="heading">
                <div class="container">
                    <div class="row d-flex justify-content-center text-center">
                        <div class="col-lg-8">
                            <h1>Blogs</h1>
                            <p class="mb-0">Dive into the world of technology, cybersecurity, and innovation through the
                                insightful articles and updates on The Visionarys Nepal Blog</p>
                        </div>
                    </div>
                </div>
            </div>
            <nav class="breadcrumbs">
                <div class="container">
                    <ol>
                        <li><a href="{% url 'home:home' %}">Home</a></li>
                        <li class="current">Blogs</li>
                    </ol>
                </div>
            </nav>
        </div>

        <section id="blog" class="blog">

            <div class="container" data-aos="" data-aos-delay="100">

                <div class="row gy-4 posts-list">

                    {% for blog in blogs %}
                        {% include "blog/includes/blog_card.html" with blog=blog %}
                    {% empty %}
                        <p>There are no posts</p>
                    {% endfor %}
                </div>

                <div class="pagination d-flex justify-content-center">
                    <ul>
                        {% if blogs.has_previous %}
                            <li>
                                <a href="?q={{ blogs.previous_page_number }}"><</a>
                            </li>
                        {% endif %}
                        <span>
                        <li class="active">
                            <a href="?q={{ blogs.number }}">{{ blogs.number }}</a>
                        </li>
                        </span>
                        {% if blogs.has_next %}
                            <li>
                                <a href="?q={{ blogs.next_page_number }}">></a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

apps/blog/templates/blog/category_page.html
{% extends "base.html" %}
{% load tz %}
{% load static %}
{% block title %}Tags{% endblock title %}
{% block content %}
<style>
    .cursor-pointer {
        cursor: pointer;
    }

    .meta-li {
        color: rgba(var(--default-color-rgb), 0.6);
        font-size: 14px;
        display: inline-block;
        line-height: 1;
        cursor: default;
    }

    .recent-posts .post-img {
        max-height: 180px;
    }

    .img-fluid {
        height: 100%;
        width: 100%;
        object-position: top;
        object-fit: cover;
    }
</style>
<main>
    <div data-aos="fade" class="page-title">
        <div class="heading">
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>{{category.name}}</h1>
                        <p class="mb-0">{{category.description}}</p>
                    </div>
                </div>
            </div>
        </div>
        <nav class="breadcrumbs">
            <div class="container">
                <ol>
                    <li><a href="{% url "home:home" %}">Home</a></li>
                    <li><a href="{% url "blog:blogs" %}">Blogs</a></li>
                    <li class="current">{{category.name}}</li>
                </ol>
            </div>
        </nav>
    </div>

    <section id="blog-details" class="blog-details">

        <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="row g-5">

                <div class="col-lg-9">

                    <section id="blogs" class="recent-posts">
                        <div class="container section-title" data-aos="fade-up">
                            <h2>Top Posts</h2>
                            <p>Here are the most viewed posts of The Visionarys Nepal.</p>
                        </div>
                        <div class="container">
                            <div class="row gy-4">
                                {% for blog in top_blogs %}
                                    {% include "blog/includes/blog_card.html" with blog=blog %}
                                {% empty %}
                                    <p>There are no posts</p>
                                {% endfor %}
                            </div>
                        </div>

                    </section>

                    <section id="blogs" class="recent-posts">
                        <div class="container section-title" data-aos="fade-up">
                            <h2>Recent Posts</h2>
                            <p>Stay updated with the latest insights, events, and news from The Visionarys Nepal community.</p>
                        </div>
                        <div class="container">
                            <div class="row gy-4">
                                {% for blog in recent_blogs %}
                                    {% include "blog/includes/blog_card.html" with blog=blog %}
                                {% empty %}
                                    <p>There are no posts</p>
                                {% endfor %}
                            </div>
                        </div>

                    </section>

                </div>

                <div class="col-lg-3">

                    <div class="sidebar">
                        <div class="sidebar-item tags">
                            <h3 class="sidebar-title">Categories</h3>
                            <ul class="mt-3">
                                {% for category in categories %}
                                <li><a href="{% url "blog:category_detail_page" category.slug %}">{{category.name}}</a></li>
                                {% endfor %}
                            </ul>
                        </div><!-- End sidebar tags-->

                    </div><!-- End Sidebar -->

                </div>

            </div>

        </div>

    </section><!-- End Blog-details Section -->
</main>

{% endblock content %}

apps/blog/templates/blog/search.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}
{% block title %}Post Title{% endblock title %}
{% block content %}
    <style>
        .cursor-pointer {
            cursor: pointer;
        }

        .meta-li {
            color: rgba(var(--default-color-rgb), 0.6);
            font-size: 14px;
            display: inline-block;
            line-height: 1;
            cursor: default;
        }

        .post-img {
            height: 100%;
        }

        .img-fluid {
            height: 100%;
            width: 100%;
            object-position: top;
            object-fit: cover;
        }
    </style>
    <main>
        <div data-aos="fade" class="page-title">
            <div class="heading">
                <div class="container">
                    <div class="row d-flex justify-content-center text-center">
                        <div class="col-lg-8">
                            <h1>Search</h1>
                            <p class="mb-0">Search for all the blogs in The Visionarys Nepal's catalog...</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section id="blog-details" class="blog-details">
            <div class="container" data-aos="fade-up" data-aos-delay="100">

                <div class="row g-5">

                    <div class="col-lg-12">
                        <div class="sidebar">
                            <div class="sidebar-item search-form">
                                <h3 class="sidebar-title">Search</h3>
                                <form method="GET" action="" class="mt-3">
                                    <input type="text" name="search" value="{{ query }}"/>
                                    <button type="submit"><i class="bi bi-search"></i></button>
                                </form>
                            </div><!-- End sidebar search form-->
                        </div><!-- End Sidebar -->
                    </div>


                    <section id="blog" class="blog">
                        <div class="container" data-aos="" data-aos-delay="100">

                            <div class="row gy-4 posts-list">

                                {% for blog in blogs %}
                                    {% include "blog/includes/blog_card.html" with blog=blog %}
                                {% empty %}
                                    <p>There are no posts</p>
                                {% endfor %}
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    </main>
{% endblock content %}

apps/blog/templates/blog/tag_page.html
{% extends "base.html" %}
{% load tz %}
{% load static %}
{% block title %}Tags{% endblock title %}
{% block content %}
<style>
    .cursor-pointer {
        cursor: pointer;
    }

    .meta-li {
        color: rgba(var(--default-color-rgb), 0.6);
        font-size: 14px;
        display: inline-block;
        line-height: 1;
        cursor: default;
    }

    .recent-posts .post-img {
        max-height: 180px;
    }

    .img-fluid {
        height: 100%;
        width: 100%;
        object-position: top;
        object-fit: cover;
    }
</style>
<main>
    <div data-aos="fade" class="page-title">
        <div class="heading">
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>{{tag.name}}</h1>
                        <p class="mb-0">{{tag.description}}</p>
                    </div>
                </div>
            </div>
        </div>
        <nav class="breadcrumbs">
            <div class="container">
                <ol>
                    <li><a href="{% url "home:home" %}">Home</a></li>
                    <li><a href="{% url "blog:blogs" %}">Blogs</a></li>
                    <li class="current">{{tag.name}}</li>
                </ol>
            </div>
        </nav>
    </div>

    <section id="blog-details" class="blog-details">

        <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="row g-5">

                <div class="col-lg-9">

                    <section id="blogs" class="recent-posts">
                        <div class="container section-title" data-aos="fade-up">
                            <h2>Top Posts</h2>
                            <p>Here are the most viewed posts of The Visionarys Nepal.</p>
                        </div>
                        <div class="container">
                            <div class="row gy-4">
                                {% for blog in top_blogs %}
                                    {% include "blog/includes/blog_card.html" with blog=blog %}
                                {% empty %}
                                    <p>There are no posts</p>
                                {% endfor %}
                            </div>
                        </div>

                    </section>

                    <section id="blogs" class="recent-posts">
                        <div class="container section-title" data-aos="fade-up">
                            <h2>Recent Posts</h2>
                            <p>Stay updated with the latest insights, events, and news from The Visionarys Nepal community.</p>
                        </div>
                        <div class="container">
                            <div class="row gy-4">
                                {% for blog in recent_blogs %}
                                    {% include "blog/includes/blog_card.html" with blog=blog %}
                                {% empty %}
                                    <p>There are no posts</p>
                                {% endfor %}
                            </div>
                        </div>

                    </section>

                </div>

                <div class="col-lg-3">

                    <div class="sidebar">
                        <div class="sidebar-item tags">
                            <h3 class="sidebar-title">Tags</h3>
                            <ul class="mt-3">
                                {% for tag in tags %}
                                <li><a href="{% url "blog:tag_detail_page" tag.slug %}">{{tag.name}}</a></li>
                                {% endfor %}
                            </ul>
                        </div><!-- End sidebar tags-->

                    </div><!-- End Sidebar -->

                </div>

            </div>

        </div>

    </section><!-- End Blog-details Section -->
</main>

{% endblock content %}