apps/blog/urls.py
from django.urls import path

from apps.blog.views import BlogDetailPageView, BlogPageView

from . import views

app_name = "blog"
urlpatterns = [
    path("", BlogPageView.as_view(), name="blogs"),
    path("blog/<slug:slug>/", BlogDetailPageView.as_view(), name="blog_detail_page"),
    path("tag/<slug:slug>/", views.TagDetailView.as_view(), name="tag_detail_page"),
    path(
        "category/<slug:slug>/",
        views.CategoryDetailView.as_view(),
        name="category_detail_page",
    ),
    path("author/<slug:slug>/", views.BlogAuthorView.as_view(), name="author"),
    path("search/", views.SearchView.as_view(), name="search"),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

admin.site.site_title = "Dashboard"
admin.site.site_header = "The Visionarys Nepal"
admin.site.index_title = "The Visionarys Nepal (TVN)"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.home.urls")),
    path("blogs/", include("apps.blog.urls")),
    path("teams/", include("apps.team.urls")),
    path("contact/", include("apps.contact.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/blog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)

        return super(Tag, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} Tag"


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    slug = models.SlugField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)

        return super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"


class Blog(models.Model):
    title = models.CharField(max_length=255)
    headline = models.CharField(max_length=255, blank=True, null=True)
    content = RichTextUploadingField()
    last_updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(null=True, blank=True, upload_to="blogs/")
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="blog_author",
    )
    tags = models.ManyToManyField(Tag, blank=True, related_name="blog_tags")
    view_count = models.IntegerField(null=True, blank=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="blog_category",
    )

    def __str__(self):
        return f"{self.title}"

    @property
    def get_author_name(self):
        return self.author.profile.get_name


class Comment(models.Model):
    user_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    content = models.TextField()
    date = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    parent = models.ForeignKey(
        "self",
        on_delete=models.DO_NOTHING,
        blank=True,
        null=True,
        related_name="replies",
    )

    def __str__(self):
        return f"{self.user_name}"

apps/blog/forms.py
from django import forms

from apps.blog.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {"user_name", "email", "content"}

        widgets = {
            "user_name": forms.TextInput(
                attrs={"placeholder": "Your Name*", "class": "form-control"}
            ),
            "email": forms.EmailInput(
                attrs={"placeholder": "Your Email*", "class": "form-control"}
            ),
            "content": forms.Textarea(
                attrs={"placeholder": "Your comment*", "class": "form-control"}
            ),
        }

apps/blog/views.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView, TemplateView

from apps.blog.forms import CommentForm
from apps.blog.models import Blog, Category, Comment, Tag


# Create your views here.
class BlogPageView(TemplateView):
    template_name = "blog/blogs.html"

    def get_context_data(self, **kwargs):
        super().get_context_data(**kwargs)
        blogs = (
            Blog.objects.all()
            .select_related("author", "category")
            .order_by("-view_count")
        )
        page_num = self.request.GET.get("q")
        paginator = Paginator(blogs, 6)
        page_obj = paginator.get_page(page_num)

        context = {"blogs": page_obj}
        return context


class BlogDetailPageView(DetailView):
    model = Blog
    template_name = "blog/blog_detail.html"

    def get_object(self, queryset=None):
        qs = (
            Blog.objects.select_related("author", "category")
            .prefetch_related(
                "comments",
                "comments__parent",
                "comments__replies",
                "author__user_socials__icon",
            )
            .annotate(total_comments=Count("comments", filter=Q(comments__parent=None)))
        )
        return get_object_or_404(qs, slug=self.kwargs["slug"])

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        blog = self.get_object()
        recent_blogs = Blog.objects.all().order_by("-last_updated")
        tags = Tag.objects.all()
        comment_form = CommentForm()
        categories = Category.objects.annotate(
            total_blogs=Count("blog_category", distinct=True)
        ).order_by("-total_blogs")

        if blog.view_count is None:
            blog.view_count = 1
        else:
            blog.view_count = blog.view_count + 1
        blog.save()

        query = self.request.GET.get("q")
        if query is not None and query != "":
            blogs = Blog.objects.filter(title__icontains=query)

        context = {
            "post": blog,
            "comment_form": comment_form,
            "recent_blogs": recent_blogs,
            "tags": tags,
            "categories": categories,
        }

        return context

    def post(self, request, *args, **kwargs):
        slug = kwargs.get("slug")
        blog_post = self.get_object()
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid:
            if request.POST.get("parent_id"):
                parent_id = request.POST.get("parent_id")
                parent = Comment.objects.get(id=parent_id)
                if parent:
                    comment_reply = comment_form.save(commit=False)
                    comment_reply.parent = parent
                    comment_reply.post = blog_post
                    comment_reply.save()
                    return render(
                        request,
                        "blog/includes/comments.html",
                        {
                            "post": self.get_object(),
                            "comment_form": CommentForm(),
                        },
                    )
            else:
                comment = comment_form.save(commit=False)
                comment.post = blog_post
                comment.save()
                return render(
                    request,
                    "blog/includes/comments.html",
                    {
                        "post": self.get_object(),
                        "comment_form": CommentForm(),
                    },
                )
        return JsonResponse({"error": "Invalid Form", "status": "500"})


class TagDetailView(DetailView):
    model = Tag
    template_name = "blog/tag_page.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Tag, slug=self.kwargs["slug"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tags = Tag.objects.exclude(slug=self.kwargs["slug"])
        tag = self.get_object()
        blogs = Blog.objects.select_related("category", "author")
        top_blogs = blogs.filter(tags__slug=tag.slug).order_by("-view_count")[:3]
        recent_blogs = blogs.filter(tags__slug=tag.slug).order_by("-last_updated")[:3]
        context.update(
            {
                "tag": tag,
                "tags": tags,
                "top_blogs": top_blogs,
                "recent_blogs": recent_blogs,
            }
        )

        return context


class BlogAuthorView(DetailView):
    template_name = "blog/author.html"
    model = User

    def get_object(self, queryset=None):
        qs = User.objects.select_related("profile").prefetch_related(
            "blog_author", "blog_author__category"
        )
        return get_object_or_404(qs, profile__slug=self.kwargs["slug"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = self.get_object()
        top_authors = (
            User.objects.select_related("profile")
            .annotate(total_blogs=Count("blog_author"))
            .order_by("-total_blogs")
        )
        top_blogs = author.blog_author.prefetch_related("category").order_by(
            "-view_count"
        )[0:3]
        recent_blogs = author.blog_author.prefetch_related("category").order_by(
            "-last_updated"
        )[0:3]
        context.update(
            {
                "author": author,
                "top_authors": top_authors,
                "top_blogs": top_blogs,
                "recent_blogs": recent_blogs,
            }
        )
        return context


class CategoryDetailView(DetailView):
    model = Category
    template_name = "blog/category_page.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Category, slug=self.kwargs["slug"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.get_object()
        categories = Category.objects.exclude(slug=self.kwargs["slug"])
        blogs = Blog.objects.select_related("author", "category")
        top_blogs = blogs.filter(category=category).order_by("-view_count")[0:3]
        recent_blogs = blogs.filter(category=category).order_by("-last_updated")[:3]
        context.update(
            {
                "category": category,
                "categories": categories,
                "top_blogs": top_blogs,
                "recent_blogs": recent_blogs,
            }
        )
        return context


class SearchView(TemplateView):
    template_name = "blog/search.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get("search")
        if query:
            blogs = Blog.objects.select_related("author", "category").filter(
                title__icontains=query
            )
            context.update(
                {
                    "blogs": blogs,
                    "query": query,
                }
            )
        return context

apps/blog/templates/blog/includes/blog_card.html
{% load tz %}
{% load static %}
<div class="col-xl-4 col-lg-6">
    <article>
        <div class="post-img">
            {% with blog_image=blog.image %}
                <img src="
                        {% if blog_image %}{{ blog_image.url }}{% else %}{% static 'assets/img/blog_static.jpg' %}{% endif %}"
                     alt="{{ blog.title }}" class="img-fluid"/>
            {% endwith %}
        </div>

        <p class="post-category">{{ blog.category.name }}</p>

        <h2 class="title">
            <a href="{% url 'blog:blog_detail_page' blog.slug %}">{{ blog.title }}</a>
        </h2>

        <div class="d-flex align-items-center gap-3">
            {% with author_image=blog.author.profile.profile_image %}
                <img src="
                        {% if author_image %}{{ author_image.url }}{% else %}{% static 'assets/img/profile.svg' %}{% endif %}"
                     alt="{{ blog.get_author_name }}"
                     class="img-fluid post-author-img flex-shrink-0">
            {% endwith %}

            <div class="post-meta">
                <p class="post-author">{{ blog.get_author_name }}</p>
                <p class="post-date">
                    <time datetime="2023-12-30">{{ blog.last_updated|timezone:"Asia/Kathmandu"|date }}</time>
                </p>
            </div>
        </div>
    </article>
</div>

apps/blog/templates/blog/includes/comment_form.html
<div class="reply-form comment-box" style="display:none">
    <h4>Reply to {{ comment.user_name }}</h4>
    <p>Your email address will not be published. Required fields are marked
        * </p>
    <form hx-post="" hx-target="#comments-body" hx-swap="innerHTML">
        {% csrf_token %}
        <input type="hidden" name="parent_id" value="{{ comment.id }}"/>
        <div class="row">
            <div class="col-md-6 form-group">
                {{ comment_form.user_name }}
            </div>
            <div class="col-md-6 form-group">
                {{ comment_form.email }}
            </div>
        </div>
        <div class="row">
            <div class="col form-group">
                {{ comment_form.website }}
            </div>
        </div>
        <div class="row">
            <div class="col form-group">
                {{ comment_form.content }}
            </div>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-primary">Reply</button>
        </div>
    </form>
</div>

apps/blog/templates/blog/includes/comment_replies.html
{% for reply in replies %}
    <div id="comment-reply-{{ reply.id }}" class="comment comment-reply ms-4">
        <div class="d-flex">
            <div class="comment-img">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
                    <circle style="fill:none;stroke:#000000;stroke-width:2;" cx="16" cy="12" r="6"/>
                    <path style="fill:none;stroke:#000000;stroke-width:2;" d="M7,27c0-4.971,4.029-9,9-9s9,4.029,9,9"/>
                </svg>
            </div>

            <div>
                <h5>
                    <span class="bold">{{ reply.user_name }}</span>
                    <span class="bold cursor-pointer" onclick="toggleDiv(this)">
                        <i class="bi bi-reply-fill"></i> Reply
                    </span>
                </h5>
                <time>{{ reply.date|date }}</time>
                <p>{{ reply.content }}</p>
                {% include "blog/includes/comment_form.html" with comment=comment %}
            </div>
        </div>
    </div>
{% endfor %}

apps/blog/templates/blog/includes/comments.html
<h4 class="comments-count">{{ post.total_comments }} Comment{{ post.total_comments|pluralize }}</h4>
{% for comment in post.comments.all %}
    {% if not comment.parent %}
        <div id="comment-{{ comment.id }}" class="comment">
            <div class="d-flex">
                <div class="comment-img">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                         viewBox="0 0 32 32">
                        <circle style="fill:none;stroke:#000000;stroke-width:2;" cx="16"
                                cy="12" r="6"/>
                        <path style="fill:none;stroke:#000000;stroke-width:2;"
                              d="M7,27c0-4.971,4.029-9,9-9s9,4.029,9,9"/>
                    </svg>
                </div>

                <div>
                    <h5>
                        <span class="bold">{{ comment.user_name }}</span>
                        <span class="bold cursor-pointer"
                              onclick="toggleDiv(this)">
                            <i class="bi bi-reply-fill"></i> Reply
                        </span>
                    </h5>
                    <time>{{ comment.date|date }}</time>
                    <p>{{ comment.content }}</p>
                    {% include "blog/includes/comment_form.html" with comment=comment %}
                </div>
            </div>

            {% if comment.replies.exists %}
                <button class="btn btn-link toggle-replies-btn"
                        onclick="toggleComments(this, 'replies-{{ comment.id }}', {{ comment.replies.count }})">
                    View Replies ({{ comment.replies.count }})
                </button>

                <div id="replies-{{ comment.id }}" class="comment-replies"
                     style="display: none;">
                    {% include "blog/includes/comment_replies.html" with replies=comment.replies.all %}
                </div>
            {% endif %}
        </div>
    {% endif %}
{% endfor %}